PREDICT_START = "<predict>"
PREDICT_END = "</predict>"
THINK_START = "<think>"
THINK_END = "</think>"
UNSOLVABLE_TOKEN = "Unsolvable"

DEFAULT_MAX_COMPLETION_TOKENS = 16384
DEFAULT_EFFICIENT_COST_PERCENTILE = 0.30
DEFAULT_SOLVABILITY_CONFIDENCE = 0.20

DECLARED_ABSTAIN_TOL = 1e-6
FORCED_ATTEMPT_BUDGET = 1.0
