PREDICT_START = "<predict>"
PREDICT_END = "</predict>"
THINK_START = "<think>"
THINK_END = "</think>"
UNSOLVABLE_TOKEN = "Unsolvable"
DEFAULT_MAX_COMPLETION_TOKENS = 16384
DEFAULT_EFFICIENT_COST_PERCENTILE = 0.30
